### PR TITLE
Remove chart to harvester/charts

### PR DESCRIPTION
**Pull request by yaocw2020**
related pr: https://github.com/harvester/charts/pull/2

### CODE REVIEW

**Review by gitlawr — APPROVED** [review]
LGTM

**Comment by guangbochen** [comment]
@yaocw2020 can u please add a link to the new helm chart repo on the README file so that users would be able to find it if needed.

**Comment by yaocw2020** [comment]
> @yaocw2020 can u please add a link to the new helm chart repo on the README file so that users would be able to find it if needed.

I think it's more reasonable to add the address of the index yaml file to be generated in the gh-page branch.

**Comment by yaocw2020** [comment]
> @yaocw2020 can u please add a link to the new helm chart repo on the README file so that users would be able to find it if needed.

Updated

**Review by guangbochen — APPROVED** [review]

**Pull request merged**
